modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/autumnity/issues"
license = "https://github.com/team-abnormals/autumnity/blob/main/LICENSE.txt"

[[mods]]
    modId = "autumnity"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "autumnity:snail_shell_piece"
    configBackground = "autumnity:textures/block/snail_shell_tiles.png"
    authors = "Team Abnormals"
    credits = "Markus1002, Farcr, five, Echolite, hatsondogs"
    displayURL = "https://www.teamabnormals.com/mods/autumnity"
    displayName = "Autumnity"
    description = '''
    An autumn-themed mod with new biomes and friendly snails.
    '''

[[dependencies.autumnity]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.autumnity]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.18,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.autumnity]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.3.0,)"
    ordering = "AFTER"
    side = "BOTH"