modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Markus1002/Autumnity/issues"
[[mods]]
modId="autumnity"
version="1.3.1"
displayName="Autumnity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autumnity"
credits="Five and Snake"
authors="Markus1002"
description='''An autumn-themed mod with new biomes and friendly snails.'''
[[dependencies.autumnity]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.49,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.autumnity]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="AFTER"
    side="BOTH"
